/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogoadivinhacao;

@import java.awt.Font;
/**
 *
 * @author Lenovo-Notebook
 */
public class JogoSimples extends javax.swing.JFrame {

    /**
     * Creates new form JogoSimples
     */
    public JogoSimples() {
        initComponents();
        lblF.setText("<html> Estou pensando em um número de <strong>1</strong> a <strong>5</strong>. tente adivinhar. </html>");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spNu = new javax.swing.JSpinner();
        bntClic = new javax.swing.JButton();
        lblF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Akinator-pq.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/balao.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 236, 236));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Valor");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 296, -1, -1));

        spNu.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(spNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 288, 38, 33));

        bntClic.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bntClic.setText("Palpite");
        bntClic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntClicActionPerformed(evt);
            }
        });
        getContentPane().add(bntClic, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 348, -1, -1));

        lblF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblF.setText("frase");
        lblF.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 140, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntClicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntClicActionPerformed
        // TODO add your handling code here:
        int palpite = Integer.parseInt(spNu.getValue().toString());
        double gerador = Math.random();
        int comp = (int)(1 + gerador * (6 - 1));
        
        String f1 = "<html>ACERTOU!</html>";
        String f2 = "<html>ERROU! O número era "+comp+"</html>";
        
        String nf = (palpite == comp)?f1:f2;
        
        lblF.setFont(new Font("Arial Black", Font.PLAIN, 14));
        
        lblF.setText(nf);
        
    }//GEN-LAST:event_bntClicActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoSimples().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntClic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblF;
    private javax.swing.JSpinner spNu;
    // End of variables declaration//GEN-END:variables
}
